version: "3"

services: 
  app:
    build: .
    command: yarn dev
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app

  db:
    container_name: 'database-node'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=America/Sao_Paulo