version: "3"

services: 
  app:
    build: .
    command: yarn dev
    ports: 
      - "3001:3001"
    volumes:
      - .:/usr/app
    networks:
      - mysql

networks: 
  mysql:
    name: mysql
    external: true